### ISSUE TITLE
need to put back the french names in the data package

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT231-S24/CanadianNutrient#7]
@javiergutierrezbach I completely misunderstood what you were doing yesterday. 

It's fine to elide the french names from your project analysis. 

But you should keep them in the package. 

Can you please move your deselection of the objects into https://github.com/STAT231-S24/proj-Chaidemenos-Gutierrez-Bach and make a new version of `CanadianNutrient` that restores this field (and ensures that the documentation is consistent with the data)?

**Comment by javiergutierrezbach** [comment]
This was done already
